version: '3'

services:
  soap-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TARGET_URL=http://test12.probizyazilim.com/Intellect/ExecuteTransaction.asmx
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped